### PR TITLE
fix(a11y): increase contrast on elements

### PR DESCRIPTION
**Pull request by varjmes**
:wave:

Hey @steveklabnik, thanks for introducing me to intermezzOS, this looks so cool. Also hi, @ashleygwilliams :)

I noticed that there were a few contrasting problems on the website:

intermezzos_before

(Analysed using [totally.js](http://khan.github.io/tota11y/))

So I updated some of the colours:

intermezzos_after

I realise you might want to go in a totally different direction, but I thought I'd at least offer up some suggestions in case they you liked them. No hard feelings whatsoever if you don't!

Thanks again, and have a calm and casual New Year.

thumbsup

### CODE REVIEW

**Comment by steveklabnik** [comment]
I do like this! We were actually split between blue and purple. If you had to pick a purple, would that be better or worse, do you think? I don't know much about contrast.

**Comment by varjmes** [comment]
I actually love purple, so I picked a nice purple:

Let me know what you think and I can change my code :)

intermezzos_after_purple

**Comment by varjmes** [comment]
Also the colour you decide on isn't the clincher. Contrast is about how readable the text element is against it's background, so we could even do rainbow if worked :)

PS. My vote is for the purple

**Comment by steveklabnik** [comment]
Blue and purple are just my favorites. :) that color looks great!

**Comment by varjmes** [comment]
Awesome, let me know which one you decide and I'll squash the commit and you can do with it what you wish :D

**Comment by steveklabnik** [comment]
I don't mind leaving this un-squashed. Thanks!

**Comment by varjmes** [comment]
:tada:

**Pull request merged**
