### PR TITLE
add twii2

### PR DESCRIPTION
**Pull request by ashleygwilliams**
- add updates to book

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
hey @steveklabnik can you link me to any speaking engagements you've had about intermezzOS? also anyone else in the community

**Comment by steveklabnik** [comment]
Only kernel PR: https://github.com/intermezzOS/kernel/pull/30

Speaking: http://www.meetup.com/BostonRust/events/230419544/

**Comment by steveklabnik** [comment]
:heart: :sparkling_heart: :heart:

**Pull request merged**
